micronaut:
  application:
    name: blog
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET:aaaa}
              jws-algorithm: HS512
endpoints:
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
  prometheus:
    enabled: true
  health:
    enabled: true
    sensitive: false
  routes:
    enabled: true
    sensitive: false

mongodb:
  uri: ${MONGO_URI:`mongodb://root:root@localhost:27017`}


