apiVersion: apps/v1
kind: Deployment
metadata:
  name: micronaut-blog
  namespace: micronaut-blog
  labels:
    app: micronaut-blog
spec:
  replicas: 1
  template:
    metadata:
      name: micronaut-blog
      labels:
        app: micronaut-blog
    spec:
      containers:
        - name: micronaut-blog
          image: uniqe15/micronaut-blog:0.17
          imagePullPolicy: IfNotPresent
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwt-secret
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: mongo-uri
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#            initialDelaySeconds: 3
#            periodSeconds: 3
      restartPolicy: Always
  selector:
    matchLabels:
      app: micronaut-blog