apiVersion: v1
kind: Service
metadata:
  name: micronaut-blog
  namespace: micronaut-blog
  labels:
    app: micronaut-blog
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/prometheus'
    prometheus.io/port:  '8080'
spec:
  selector:
    app: micronaut-blog
  ports:
    - name: http-server
      port: 8080
  type: NodePort
