apiVersion: v1
kind: Service
metadata:
  name: micronaut-blog
  namespace: micronaut-blog
  labels:
    http-app: true
spec:
  selector:
    app: micronaut-blog

  ports:
    - name: http-server
      port: 8080
  type: NodePort